### ISSUE TITLE
Update readme.md to remove dev environment setup

### ISSUE THREAD

**Issue by MiguelCastillo** [Brackets-Themes/BoilerPlate#3]
Now that themes is in brackets core, we no longer need the dev env setup instruction.

**Comment by wormeyman** [comment]
I thought that is what i did in c8c73c10a06df2a152b898a3126137a543e0a086 and 095478d32b524771602b71d2259cac4d831d3124? Did i miss something?

**Comment by MiguelCastillo** [comment]
OH, somehow I was getting the page with the dev setup.  My bad, closing.
