### ISSUE TITLE
Need Delko's Dark theme for Phpstorm 

### ISSUE THREAD

**Issue by codychia** [Brackets-Themes/BoilerPlate#6]
## Basic scenarios
1. 1. Programmer should have the theme to php storm too
2. 2.Below are the guildlines , on how you can can configure them .
3. Thanks :)
- https://www.jetbrains.com/help/phpstorm/2016.1/configuring-colors-and-fonts.html

**Comment by ErikThiart** [comment]
Plus 1

Please make this theme open to being ported to PHPstorm.

**Comment by MiguelCastillo** [comment]
Hello! What do you mean open to being ported? This all should be open source. Currently I dont have the cycles to create a theme... But please do feel free to create one and I would be happy to add it to the Brackets-Themes organization.
